services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    hostname: openwebui
    ports:
      - 8800:8080
    networks:
      - ansagpt
    restart: unless-stopped
    volumes:
      - ./data/openwebui-data:/app/backend/data
    environment:
      OLLAMA_BASE_URLS: http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    networks:
      - chatlocalgpt
    volumes:
      - ./data/ollama-data:/root/.ollama

networks:
  chatlocalgpt:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: chatlocalgpt