services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    hostname: openwebui
    ports:
      - 8800:8080
    networks:
      - ansagpt
    restart: unless-stopped
    volumes:
      - ./data/openwebui-data:/app/backend/data
    environment:
      OLLAMA_BASE_URLS: http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_IGPU_ENABLE=1
      - XDG_RUNTIME_DIR=/tmp/runtime
      - OLLAMA_NUM_GPU=1
      - OLLAMA_GPU_LAYER=all
      - OLLAMA_VULKAN=1
    tmpfs:
      - /tmp/runtime
    devices:
      - /dev/dri:/dev/dri
    networks:
      - chatlocalgpt
    volumes:
      - ./data/ollama-data:/root/.ollama
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      - /usr/share/drirc.d:/usr/share/drirc.d:ro
      - /usr/share/glvnd/egl_vendor.d:/usr/share/glvnd/egl_vendor.d:ro

networks:
  chatlocalgpt:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: chatlocalgpt